# Generated by Django 5.0.3 on 2024-04-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('blood_group', models.CharField(max_length=5)),
                ('diagnosis', models.CharField(max_length=255)),
                ('allergies', models.TextField(blank=True)),
                ('contraindications', models.TextField(blank=True)),
                ('guardian_contact', models.CharField(max_length=20)),
                ('hospital', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'PersonalData',
                'verbose_name_plural': 'PersonalDataset',
            },
        ),
    ]
