# Generated by Django 5.0.3 on 2024-04-21 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_personaldata_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldata',
            name='image',
        ),
    ]
