# Generated by Django 5.0.3 on 2024-04-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_personaldata_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaldata',
            old_name='full_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='personaldata',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='surename',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
