# Generated by Django 5.0.4 on 2024-04-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_full_name_personaldata_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldata',
            name='surename',
        ),
        migrations.AddField(
            model_name='personaldata',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='personaldata',
            name='surname',
            field=models.CharField(default='Turganbek', max_length=255),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='guardian_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='hospital',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='name',
            field=models.CharField(default='Nurzat', max_length=255),
        ),
    ]
