# Generated by Django 5.0.4 on 2024-04-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_personaldata_surename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldata',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='contraindications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
