# Generated by Django 5.0.4 on 2024-05-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_personaldata_allergies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldata',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
