# Generated by Django 5.0.4 on 2024-05-02 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
